In [1]:
import pandas as pd

Utiizando operadores para formar condições e filtrar saída de dados.

In [ ]:
dados = {
    'Produto' : ['Celular','TV','Fone de ouvido','Microfone'],
    'Valor' : [ 3000,5000,120,2000],
    'Quantidade' : [50,30,40,5]
}

df = pd.DataFrame(dados)

filtro = df[(df['Valor']>150) &(df['Quantidade'] >10)] # resgatar valores cujo o Valor seja maior que 150 E(operador and) Quantidade seja maior que 10.
    # Está sendo utilizado o operador AND, ou seja ambas condições devem ser verdadeiras, caso só uma for, nenhum valor será mostrado na saída.
    
print("Valores maiores que 150 e quantidade maior que 10:")
filtro

Valores maiores que 150 e quantidade maior que 10:

   Produto  Valor  Quantidade
0  Celular   3000          50
1       TV   5000          30

In [ ]:
# filtrar informação dos produtos cujo a Quantidade seja inferior a 50

dados = {
    'Produto' : ['Caderno','Lápis','Caneta','Estojo'],
    "Quantidade" : [10,27,54,4]
}

df = pd.DataFrame(dados)

filtro = df[df['Quantidade']<50] 
print ("Produtos com quantidade abaixo de 50:")
filtro

Produtos com quantidade abaixo de 50:

   Produto  Quantidade
0  Caderno          10
1    Lápis          27
3   Estojo           4

In [ ]:
# filtrar informação dos funcionários cujo o Departamento seja de Vendas

dados = {
    'Nome' : ['João','Maria','Milene','Richard'],
    'Salário' :[2000,1600,800,2500],
    'Departamento': ['Vendas','RH','Financeiro','Vendas']

}

df = pd.DataFrame(dados)
filtro = df[df['Departamento']=='Vendas']  
filtro

      Nome  Salário Departamento
0     João     2000       Vendas
3  Richard     2500       Vendas

In [ ]:
#filtrar informações dos Alunos cujo a idade seja igual ou maior a 28.

dados = {
    'Nome' : ['João','Maria','Ana','Roberta','Letícia'],
    'Curso' : ['TI','Artes','Direito','Pedagogia','Ed.Física'],
    'Idade' : [25,28,35,42,18]
}

df = pd.DataFrame(dados)
filtro = df[df['Idade']>=28] 
filtro

      Nome      Curso  Idade
1    Maria      Artes     28
2      Ana    Direito     35
3  Roberta  Pedagogia     42

In [ ]:
# filtrar os medicamentos que tenham menos de 10 Unidades E o preço maior que 20 

dados  = {
    'Medicamento':['Dipirona','Dorflex','Omeprazol','Neosaldina'],
    'Unidade':[4,3,15,19],
    'Preço' : [4.50,25,22,18.25]

}

df = pd.DataFrame(dados)
filtro = df[(df['Unidade'] < 10) & (df['Preço']>20)] 
filtro

  Medicamento  Unidade  Preço
1     Dorflex        3   25.0

In [ ]:
# filtrar Alunos cujo a Idade seja Maior que 20 e o Curso seja "TI"

dados = {
    'Nome' : ['João','Maria','Ana','Roberta','Letícia'],
    'Curso' : ['TI','Artes','Direito','Pedagogia','Ed.Física'],
    'Idade' : [25,28,35,42,18]
}

df = pd.DataFrame(dados)
filtro = df[(df['Idade']>20) & (df['Curso'] =='TI')] 
filtro

   Nome Curso  Idade
0  João    TI     25