Utilizando Pandas para extrair MÉDIA, MEDIANA E MODA

In [1]:
import pandas as pd

In [2]:
#Criando Lista de Dados

dados = {
    'Marca' : ['Dell','HP','Lenovo','Apple'],
    'Modelos' : ['Inspiron 15','Pavilion','Thinkpad','Macbook Air'],
    'Armazenamento (GB)' : ['500 GB', '700 GB','1TB','2TB'],
    'RAM (GB)' :['120GB','250GB','500GB','700GB']
}

df = pd.DataFrame(dados)
df ['Quantidade'] = [15,30,50,40]
df

    Marca      Modelos Armazenamento (GB) RAM (GB)  Quantidade
0    Dell  Inspiron 15             500 GB    120GB          15
1      HP     Pavilion             700 GB    250GB          30
2  Lenovo     Thinkpad                1TB    500GB          50
3   Apple  Macbook Air                2TB    700GB          40

In [ ]:
dados = {
    'Produto' : ['Celular','Computador','Notebook','Videogame'],
    'Quantidade' :[6,5,20,4],
    'Preço' : [2500,4000,2200,5000],
    'Data' : ['23/03','21/03','20/03','01/01']
}

df = pd.DataFrame(dados)
df ['Total'] = (df['Quantidade'] * df['Preço']) # Cria uma nova coluna com nome "Total" , sendo o seu valor a multiplicação da Quantidade com o Preço
#df <-- print

df.rename(columns={'Quantidade':'Quantidade Vendida'}, inplace= True) # renomeia o nome da coluna | Inplace=True --> a alteração é feita diretamente do dataframe original
df

      Produto  Quantidade Vendida  Preço   Data  Total
0     Celular                   6   2500  23/03  15000
1  Computador                   5   4000  21/03  20000
2    Notebook                  20   2200  20/03  44000
3   Videogame                   4   5000  01/01  20000

In [4]:
dados= {
    'Nomes' : ['Ana','Fabrício','Juliana', 'Romero Brito'],
    'Altura' : [1.50,2.10,1.65,1.80]
}

df = pd.DataFrame(dados)

média = df['Altura'].mean()  # média --> soma todo os valores, e divide o resultado pela quantidade de elementos
mediana = df['Altura'].median() # median -->  pega o valor que está localizado no centro | se qtd de elementos for Par, ele soma os dois centrais e divide por 2.
moda = df['Altura'].mode() # apresenta o elemento que mais se repete, caso nn haja repetição ele pega o primeiro valor


print("A média é: ",média)
print("A mediana é :" , mediana)
print("a moda é : " , moda)

A média é:  1.7625
A mediana é : 1.725
a moda é :  0    1.50
1    1.65
2    1.80
3    2.10
Name: Altura, dtype: float64

In [5]:
dados = {
    'Nome':['Robson','Pietro','Diego','Rafael'],
    'Cargo':['Presidente','Diretor','Analista','Estagiário'],
    'Salário':[15000,7500,5000,1300]
}
df = pd.DataFrame(dados)

média = df['Salário'].mean()
print("Valor da média:" , média)

mediana = df ['Salário'].median()
print ("Valor da Mediana: ",mediana)

moda = df['Salário'].mode()
print("Valor da moda: " , moda)

Valor da média: 7200.0
Valor da Mediana:  6250.0
Valor da moda:  0     1300
1     5000
2     7500
3    15000
Name: Salário, dtype: int64

In [6]:
dados = {
    'Dia' :['Segunda','Terça','Quarta','Quinta','Sexta'],
    'Temperatura': [21,19,24,27,16]

}

df = pd.DataFrame(dados)

média = df ['Temperatura'].mean()
print("A temperatura média é: ", média)

moda = df ['Temperatura'].mode()
print("A moda entre as temperaturas é:" , moda)


mediana = df ['Temperatura'].median()
print("A mediana é:" , mediana)

A temperatura média é:  21.4
A moda entre as temperaturas é: 0    16
1    19
2    21
3    24
4    27
Name: Temperatura, dtype: int64
A mediana é: 21.0

In [ ]:
dados = {
    'Preços' : [200,300,500,200,600,150]
}

df = pd.DataFrame(dados)

media = df['Preços'].mean()
mediana =  df['Preços'].median()
moda =  df['Preços'].mode()

print(media)
print(mediana)
print(moda)